# Generated by Django 4.1.7 on 2023-05-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Place', models.CharField(max_length=50)),
                ('Phone', models.IntegerField()),
                ('Email', models.CharField(max_length=50)),
                ('Password', models.CharField(max_length=50)),
                ('OldPassword', models.CharField(max_length=50)),
                ('NewPassword', models.CharField(max_length=50)),
                ('ConfirmPassword', models.CharField(max_length=50)),
            ],
        ),
    ]
